gui:
  nerdFontsVersion: "3"
  showIcons: true
  showFileTree: true
  showBottomLine: true
  showCommandLog: false
  showRandomTip: false
  scrollHeight: 2
  scrollPastBottom: true
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: false
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    cherryPickedCommitBgColor:
      - "#45475a"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    unstagedChangesColor:
      - "#f38ba8"
git:
  pagers:
    - colorArg: always
      pager: delta --dark --paging=never
  commit:
    signOff: false
    verbose: default
  merging:
    manualCommit: false
    args: ""
  log:
    order: topo-order
    showGraph: always
    showWholeGraph: false
  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  fetchAll: true
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  overrideGpg: false
  disableForcePushing: false
  allBranchesLogCmds:
    - git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium
os:
  editPreset: vim
  edit: "vim {{filename}}"
  editAtLine: "vim +{{line}} {{filename}}"
  editAtLineAndWait: "vim +{{line}} {{filename}}"
  openDirInEditor: "vim {{dir}}"
refresher:
  refreshInterval: 10
  fetchInterval: 60
update:
  method: never
confirmOnQuit: false
quitOnTopLevelReturn: false
disableStartupPopups: true
notARepository: prompt
promptToReturnFromSubprocess: true
keybinding:
  universal:
    quit: "q"
    quit-alt1: "<c-c>"
    return: "<esc>"
    togglePanel: "<tab>"
    prevItem: "k"
    nextItem: "j"
    prevItem-alt: "<up>"
    nextItem-alt: "<down>"
    prevPage: "<c-b>"
    nextPage: "<c-f>"
    gotoTop: "g"
    gotoBottom: "G"
    prevBlock: "h"
    nextBlock: "l"
    prevBlock-alt: "<left>"
    nextBlock-alt: "<right>"
    nextMatch: "n"
    prevMatch: "N"
    startSearch: "/"
    optionMenu: "<disabled>"
    optionMenu-alt1: "?"
    select: "<space>"
    goInto: "<enter>"
    confirm: "<enter>"
    remove: "d"
    new: "n"
    edit: "e"
    openFile: "o"
    scrollUpMain: "<pgup>"
    scrollDownMain: "<pgdown>"
    scrollUpMain-alt1: "K"
    scrollDownMain-alt1: "J"
    scrollUpMain-alt2: "<c-u>"
    scrollDownMain-alt2: "<c-d>"
    executeShellCommand: ":"
    createRebaseOptionsMenu: "m"
    pushFiles: "P"
    pullFiles: "p"
    refresh: "R"
    createPatchOptionsMenu: "<c-p>"
    nextTab: "]"
    prevTab: "["
    undo: "z"
    redo: "<c-z>"
    copyToClipboard: "<c-o>"
    submitEditorText: "<enter>"
    filteringMenu: "<c-s>"
    diffingMenu: "W"
    diffingMenu-alt: "<c-e>"
  files:
    commitChanges: "c"
    commitChangesWithoutHook: "w"
    amendLastCommit: "A"
    commitChangesWithEditor: "C"
    ignoreFile: "i"
    refreshFiles: "r"
    stashAllChanges: "s"
    viewStashOptions: "S"
    toggleStagedAll: "a"
    viewResetOptions: "D"
    fetch: "f"
    toggleTreeView: "`"
  branches:
    createPullRequest: "o"
    viewPullRequestOptions: "O"
    checkoutBranchByName: "c"
    forceCheckoutBranch: "F"
    rebaseBranch: "r"
    renameBranch: "R"
    mergeIntoCurrentBranch: "M"
    viewGitFlowOptions: "i"
    fastForward: "f"
    pushTag: "P"
    setUpstream: "u"
    fetchRemote: "f"
  commits:
    squashDown: "s"
    renameCommit: "r"
    renameCommitWithEditor: "R"
    viewResetOptions: "g"
    markCommitAsFixup: "f"
    createFixupCommit: "F"
    squashAboveCommits: "S"
    moveDownCommit: "<c-j>"
    moveUpCommit: "<c-k>"
    amendToCommit: "A"
    pickCommit: "p"
    revertCommit: "t"
    cherryPickCopy: "c"
    cherryPickCopyRange: "C"
    pasteCommits: "v"
    tagCommit: "T"
    checkoutCommit: "<space>"
    resetCherryPick: "<c-R>"
    copyCommitMessageToClipboard: "<c-y>"
  stash:
    popStash: "g"
  commitFiles:
    checkoutCommitFile: "c"
  main:
    toggleDragSelect: "v"
    toggleDragSelect-alt: "V"
    toggleSelectHunk: "a"
    pickBothHunks: "b"
  submodules:
    init: "i"
    update: "u"
    bulkMenu: "b"
