[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = "release"
hook_add = '''
  source ~/.config/nvim/plugin/coc.vim
'''

[[plugins]]
repo = 'yuki-yano/fzf-preview.vim'

[[plugins]]
repo = 'mhinz/vim-startify'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.config/nvim/plugin/lightline.vim
'''

[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = '''
  source ~/.config/nvim/plugin/vista.vim
'''

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'mbbill/undotree'
hook_add = '''
  nnoremap <F5> :UndotreeToggle<CR>
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'mattn/sonictemplate-vim'
hook_add = '''
  let g:sonictemplate_vim_template_dir = expand('~/.config/nvim/sonictemplate')
'''

[[plugins]]
repo = 'SirVer/ultisnips'
hook_add = '''
  let g:UltiSnipsExpandTrigger="<s-tab>"
  let g:UltiSnipsJumpForwardTrigger="<c-b>"
  let g:UltiSnipsJumpBackwardTrigger="<c-z>"
  let g:UltiSnipsEditSplit="vertical"
'''

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'preservim/nerdcommenter'

[[plugins]]
repo = 'justinmk/vim-sneak'

[[plugins]]
repo = 'unblevable/quick-scope'

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
  let g:neoterm_default_mod='belowright'
  let g:neoterm_size=10
  let g:neoterm_autoscroll=1
  tnoremap <silent> <C-w> <C-\><C-n><C-w>
  nnoremap <silent> <C-n> :TREPLSendLine<CR>j0
  vnoremap <silent> <C-n> V:TREPLSendSelection<CR>'>j0
'''

[[plugins]]
repo = 'Shougo/vinarise.vim'
hook_add = '''
  augroup BinaryXXD
    autocmd!
    autocmd BufReadPre  *.bin let &binary =1
    autocmd BufReadPost * if &binary | Vinarise
    autocmd BufWritePre * if &binary | Vinarise | endif
    autocmd BufWritePost * if &binary | Vinarise
  augroup END
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'numirias/semshi'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'lervag/vimtex'
hook_add = '''
  source ~/.config/nvim/plugin/vimtex.vim
'''
