memodir = "~/Dropbox/md/memo/"
memotemplate = "~/Dropbox/md/memo/template.md"
editor = "vim"
column = 30
selectcmd = "fzf"
grepcmd = "rg -nH ${PATTERN} ${FILES}"
ssetsdir = "~/Dropbox/md/memo/assets/"
pluginsdir = "~/.config/memo/plugins/"
