[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = 'source ~/.config/nvim/plugins/plugin-dein.vim'

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'airblade/vim-rooter'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/echodoc.vim'
hook_add = 'source ~/.config/nvim/plugins/plugin-echodoc.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/vinarise.vim'
hook_add = '''
  augroup BinaryXXD
    autocmd!
    autocmd BufReadPre  *.bin let &binary =1
    autocmd BufReadPost * if &binary | Vinarise
    autocmd BufWritePre * if &binary | Vinarise | endif
    autocmd BufWritePost * if &binary | Vinarise
  augroup END
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'goolord/alpha-nvim'
hook_add = '''
  source ~/.config/nvim/plugins/lua/plugin-alpha.lua
'''
[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  source ~/.config/nvim/plugins/plugin-lightline.vim
'''

[[plugins]]
repo = 'itchyny/vim-gitbranch'

[[plugins]]
repo = 'whatyouhide/vim-gotham'
hook_add = '''
  colorscheme gotham256
'''

[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = '''
  source ~/.config/nvim/plugins/plugin-vista.vim
'''

[[plugins]]
repo = '5t111111/alt-gtags.vim'

[[plugins]]
repo = 'miyakogi/seiya.vim'
hook_add = 'source ~/.config/nvim/plugins/plugin-seiya.vim'

[[plugins]]
repo = 'mbbill/undotree'
hook_add = '''
  nnoremap <F5> :UndotreeToggle<CR>
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'terryma/vim-expand-region'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'preservim/nerdcommenter'

[[plugins]]
repo = 'justinmk/vim-sneak'

[[plugins]]
repo = 'unblevable/quick-scope'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-scripts/AnsiEsc.vim'

[[plugins]]
repo = 'numirias/semshi'

# pandoc markdown
[[plugins]]
repo = 'vim-pandoc/vim-pandoc'
hook_add = 'source ~/.config/nvim/plugins/plugin-vim-pandoc.vim'

[[plugins]]
repo = 'vim-pandoc/vim-pandoc-syntax'

# ime
[[plugins]]
repo = 'tyru/eskk.vim'
hook_add = 'source ~/.config/nvim/plugins/plugin-eskk.vim'

# english words dictionary
[[plugins]]
repo = 'koron/codic-vim'
